apiVersion: v1
kind: Service
metadata:
  name: react-app
  namespace: default
spec:
  selector:
    app: react-app
  type: LoadBalancer
  ports:
  - name: react-app
    protocol: TCP
    port: 80
    targetPort: 3000
